const nhl_abbrev = {
  "Atlanta Flames": "AFM",
  "Mighty Ducks of Anaheim/Anaheim Ducks": "ANA",
  "Arizona Coyotes": "ARI",
  "Atlanta Thrashers": "ATL",
  "Boston Bruins": "BOS",
  "Brooklyn Americans": "BRK",
  "Buffalo Sabres": "BUF",
  "Carolina Hurricanes": "CAR",
  "Columbus Blue Jackets": "CBJ",
  "Bay Area Seals/California Golden Seals": "CGS",
  "Calgary Flames": "CGY",
  "Chicago Black Hawks/Blackhawks": "CHI",
  "Cleveland Barons": "CLE",
  "Colorado Rockies": "CLR",
  "Colorado Avalanche": "COL",
  "Dallas Stars": "DAL",
  "Detroit Cougars": "DCG",
  "Detroit Red Wings": "DET",
  "Detroit Falcons": "DFL",
  "Edmonton Oilers": "EDM",
  "Florida Panthers": "FLA",
  "Hamilton Tigers": "HAM",
  "Hartford Whalers": "HFD",
  "Kansas City Scouts": "KCS",
  "Los Angeles Kings": "LAK",
  "Minnesota Wild": "MIN",
  "Montreal Maroons": "MMR",
  "Minnesota North Stars": "MNS",
  "Montreal Canadiens": "MTL",
  "Montreal Wanderers": "MWN",
  "New Jersey Devils": "NJD",
  "Nashville Predators": "NSH",
  "New York Americans": "NYA",
  "New York Islanders": "NYI",
  "New York Rangers": "NYR",
  "California/Oakland Seals": "OAK",
  "Ottawa Senators": "OTT",
  "Philadelphia Flyers": "PHI",
  "Phoenix Coyotes": "PHX",
  "Pittsburgh Pirates": "PIR",
  "Pittsburgh Penguins": "PIT",
  "Quebec Bulldogs": "QBD",
  "Philadelphia Quakers": "QUA",
  "Quebec Nordiques": "QUE",
  "Seattle Kraken": "SEA",
  "Ottawa Senators (original)": "SEN",
  "St. Louis Eagles": "SLE",
  "San Jose Sharks": "SJS",
  "St. Louis Blues": "STL",
  "Toronto Hockey Club/Toronto Arenas": "TAN",
  "Tampa Bay Lightning": "TBL",
  "Toronto Maple Leafs": "TOR",
  "Toronto St. Patricks": "TSP",
  "Vancouver Canucks": "VAN",
  "Vegas Golden Knights": "VGK",
  "Winnipeg Jets (original)": "WIN",
  "Winnipeg Jets": "WPG",
  "Washington Capitals": "WSH",
};

const nfl_abbrev = {
  "Arizona Cardinals": "ARI",
  "Atlanta Falcons": "ATL",
  "Baltimore Ravens": "BAL",
  "Buffalo Bills": "BUF",
  "Carolina Panthers": "CAR",
  "Chicago Bears": "CHI",
  "Cincinnati Bengals": "CIN",
  "Cleveland Browns": "CLE",
  "Dallas Cowboys": "DAL",
  "Denver Broncos": "DEN",
  "Detroit Lions": "DET",
  "Green Bay Packers": "GB",
  "Houston Texans": "HOU",
  "Indianapolis Colts": "IND",
  "Jacksonville Jaguars": "JAC",
  "Kansas City Chiefs": "KC",
  "Las Vegas Raiders": "LV",
  "Los Angeles Chargers": "LAC",
  "Los Angeles Rams": "LAR",
  "Miami Dolphins": "MIA",
  "Minnesota Vikings": "MIN",
  "New England Patriots": "NE",
  "New Orleans Saints": "NO",
  "New York Giants": "NYG",
  "New York Jets": "NYJ",
  "Philadelphia Eagles": "PHI",
  "Pittsburgh Steelers": "PIT",
  "San Francisco 49ers": "SF",
  "Seattle Seahawks": "SEA",
  "Tampa Bay Buccaneers": "TB",
  "Tennessee Titans": "TEN",
  "Washington Football Team": "WAS",
  "Washington Redskins": "WAS",
};

const nba_abbrev = {
  "Atlanta Hawks": "ATL",
  "Brooklyn Nets": "BKN",
  "Boston Celtics": "BOS",
  "Charlotte Hornets": "CHA",
  "Chicago Bulls": "CHI",
  "Cleveland Cavaliers": "CLE",
  "Dallas Mavericks": "DAL",
  "Denver Nuggets": "DEN",
  "Detroit Pistons": "DET",
  "Golden State Warriors": "GSW",
  "Houston Rockets": "HOU",
  "Indiana Pacers": "IND",
  "Los Angeles Clippers": "LAC",
  "Los Angeles Lakers": "LAL",
  "Memphis Grizzlies": "MEM",
  "Miami Heat": "MIA",
  "Milwaukee Bucks": "MIL",
  "Minnesota Timberwolves": "MIN",
  "New Orleans Pelicans": "NOP",
  "New York Knicks": "NYK",
  "Oklahoma City Thunder": "OKC",
  "Orlando Magic": "ORL",
  "Philadelphia 76ers": "PHI",
  "Phoenix Suns": "PHX",
  "Portland Trail Blazers": "POR",
  "Sacramento Kings": "SAC",
  "San Antonio Spurs": "SAS",
  "Toronto Raptors": "TOR",
  "Utah Jazz": "UTA",
  "Washington Wizards": "WAS",
};

const mlb_abbrev = {
  "Anaheim Angels": "ANA",
  "Arizona Diamondbacks": "ARI",
  "Atlanta Braves": "ATL",
  "Baltimore Orioles": "BAL",
  "Boston Red Sox": "BOR",
  "Chicago Cubs": "CHC",
  "Chicago White Sox": "CWS",
  "Cincinnati Reds": "CIN",
  "Cleveland Indians": "CLE",
  "Colorado Rockies": "COL",
  "Detroit Tigers": "DET",
  "Florida Marlins": "FLA",
  "Houston Astros": "HOU",
  "Kansas City Royals": "KC",
  "Los Angeles Angels": "LAA",
  "Los Angeles Dodgers": "LAD",
  "Miami Marlins": "MIA",
  "Milwaukee Brewers": "MIL",
  "Minnesota Twins": "MIN",
  "Montreal Expos": "MTL",
  "New York Mets": "NYM",
  "New York Yankees": "NYY",
  "Oakland Athletics": "OAK",
  "Philadelphia Athletics": "PHA",
  "Philadelphia Phillies": "PHI",
  "Pittsburgh Pirates": "PIT",
  "San Diego Padres": "SD",
  "Seattle Mariners": "SEA",
  "San Francisco Giants": "SF",
  "St. Louis Cardinals": "STL",
  "Tampa Bay Rays": "TB",
  "Texas Rangers": "TEX",
  "Toronto Blue Jays": "TOR",
  "Washington Nationals": "WSH",
};

module.exports = {
  mlb_abbrev,
  nfl_abbrev,
  nhl_abbrev,
  nba_abbrev,
};
